name: Build and Scan

env:
  tags: 'github,actions,github-actions,gradle'
  projectKey: 'demo:github-actions-gradle'

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  # schedule:
  #  - cron: '17 0 * * 4'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Java version
        run: |
          java -version
      # Step not needed: JDK 11 is the default on ubuntu latest
      # - name: Set up JDK 11
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 11
      - name: Fetch SonarQube Scanner cache
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Fetch Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build Gradle project
        working-directory: ./comp-gradle
        run: ./gradlew build
      - name: Analyze Gradle project
        working-directory: ./comp-gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew -d sonarqube --info
      - name: Set SonarQube project tags
        run: |
          # Set project tags on the fly
          curl -X POST -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/project_tags/set?project=${{env.projectKey}}&tags=${{env.tags}}"
